src/main/java/com/sechristfamily/blog/models/PostViewModel.java
package com.sechristfamily.blog.models;

import java.util.Date;
import java.util.Set;

public interface PostViewModel {
	
	/**
	 * Gets the title of the post
	 * @return String
	 */
	String getTitle();
	
	/**
	 * Gets the text of the post
	 * @return String
	 */
	String getText();
	
	/**
	 * Gets the date posted
	 * @return Date
	 */
	Date getDatePosted();
	
	/**
	 * Returns whether the post is published
	 * @return Boolean
	 */
	Boolean isPublished();
	
	/**
	 * Gets the associated tags
	 * @return Set
	 */
	Set<TagModel> getTags();
	
	/**
	 * Gets the title of the next oldest post
	 * @return String
	 */
	String getOlderPostTitle();
	
	/**
	 * Gets the title of the next newest post
	 * @return String
	 */
	String getNewerPostTitle();

}

src/main/java/com/sechristfamily/blog/facelets/UserServiceBean.java
package com.sechristfamily.blog.facelets;

import java.io.IOException;

import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

import com.sechristfamily.blog.security.MutableUserService;
import java.io.Serializable;

@Named
@SessionScoped
public class UserServiceBean implements Serializable, MutableUserService {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -1842007732299494581L;

	@Inject
	private FacesContext facesContext;

	private boolean isLoggedIn;
	private String logoutUri;
	private String accountUri;
	private String userEmail;
	
	public boolean isLoggedIn() {
		return isLoggedIn;
	}

	public void setIsLoggedIn(boolean isLoggedIn) {
		this.isLoggedIn = isLoggedIn;
	}
	
	public void login() {
		if (!isLoggedIn)
			facesContext.getExternalContext().invalidateSession();
		try {
			facesContext.getExternalContext().redirect(getContextUrl() + "/");
		} catch (IOException e) {
		}
	}
	
	public void logout() {
		facesContext.getExternalContext().invalidateSession();
		((HttpServletRequest)facesContext.getExternalContext()
		                .getRequest()).getSession().invalidate();
		try {
		        facesContext.getExternalContext()
		                .redirect(getLogoutUri());
		} catch (IOException e) {
		        // Do nothing
		}
	}
	
	public String getLogoutUri() {
		return logoutUri;
	}

	public void setLogoutUri(String logoutUri) {
		this.logoutUri = logoutUri;
	}
	
	public String getAccountUri() {
		return accountUri;
	}
	
	public void setAccountUri(String accountUri) {
		this.accountUri = accountUri;
	}
	
	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
	
	private String getContextUrl() {
		HttpServletRequest request = (HttpServletRequest)facesContext.getExternalContext().getRequest();
		return request.getScheme() + "://" + request.getServerName() 
				+ ":" + request.getServerPort() + request.getContextPath();
	}

}

src/main/webapp/posts/tag.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

<f:metadata>
	<f:viewParam name="name" value="#{displayTagBean.tagName}" />
</f:metadata>

<h:head></h:head>

<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="extraStyle">
			<h:panelGroup rendered="#{!userServiceBean.loggedIn}">
				<link rel="import" href="#{request.contextPath}/templates/post-tag-list.html" />
			</h:panelGroup>
			<h:panelGroup rendered="#{userServiceBean.loggedIn}">
				<link rel="import" href="#{request.contextPath}/templates/post-tag-list-admin.html" />
			</h:panelGroup>
		</ui:define>
	
		<ui:define name="pageTitle">Sechrist Blog - Tag: 
			<h:outputText value="#{displayTagBean.tagName}" />
		</ui:define>

		<ui:define name="content">
			<h3>
				Posts with the Tag:
				<h:outputText value="#{displayTagBean.tagName}" />
			</h3>
			<h:panelGroup rendered="#{!userServiceBean.loggedIn}">
				<post-tag-list tag="#{displayTagBean.tagName}"></post-tag-list>
			</h:panelGroup>
			<h:panelGroup rendered="#{userServiceBean.loggedIn}">
				<post-tag-list-admin tag="#{displayTagBean.tagName}"></post-tag-list-admin>
			</h:panelGroup>
		</ui:define>

		<ui:define name="extraScripts">
			<script>
			$('.deletePost').on("click", function() {
				var r=confirm("Are you sure you want to delete this Post forever?");
				if (r==true) {
					$.ajax({
					    url: CONTEXT_URL + '/api/posts/' + $(this).data("id"),
					    type: 'DELETE',
					    success: function(result) {
					        location.reload();
					    }
					});
				}
				return false;
			});
		</script>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/posts/view.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

<f:metadata>
	<f:viewParam name="t" value="#{displayPostBean.post}"
		converter="com.sechristfamily.blog.PostViewTitleConverter"
		converterMessage="Unknown Post! Try Again!" />
</f:metadata>

<h:head></h:head>

<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="pageTitle">
			<h:outputText value="#{displayPostBean.post.title}" />
		</ui:define>

		<ui:define name="content">
			<div id="fb-root"></div>
			<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>

			<div class="container">
				<div class="col-sm-8">
					<h1>
						<h:messages styleClass="list-unstyled" />
						<h:outputText value="#{displayPostBean.post.title}" />
						<h:outputText id="urlTitle" value="#{displayPostBean.post.title}" 
							converter="com.sechristfamily.blog.PostTitleUrlConverter" style="display: none;"/>
					</h1>
					<h4 id="date">
						<h:outputText value="#{displayPostBean.post.datePosted}">
							<f:convertDateTime pattern="dd.MMMM.yyyy" />
						</h:outputText>
					</h4>
					<div class="thin-line col-sm-12"></div>
					<div id="textBody">
						<h:outputText value="#{displayPostBean.post.text}" escape="false">
							<f:converter
								converterId="com.sechristfamily.blog.PostTextConverter" />
						</h:outputText>
						<div id="tags">
							<h:outputText value="#{displayPostBean.post.tags}" escape="false">
								<f:converter converterId="com.sechristfamily.blog.TagConverter" />
							</h:outputText>
						</div>
						<div class="clearfix"></div>
						
						<ul class="pager">
							<h:panelGroup rendered="#{displayPostBean.post.olderPostTitle == null}">
						  		<li class="previous disabled"><a href="">← Older</a></li>
						  	</h:panelGroup>
						  	<h:panelGroup rendered="#{displayPostBean.post.olderPostTitle != null}">
						  		<li class="previous">
						  			<h:outputLink value="#{request.contextPath}/posts/#{displayPostBean.post.olderPostTitle}"
						  				converter="com.sechristfamily.blog.PostTitleUrlConverter">
						  				← Older
						  			</h:outputLink>
						  		</li>
						  	</h:panelGroup>
							<h:panelGroup rendered="#{displayPostBean.post.newerPostTitle == null}">
						  		<li class="next disabled"><a href="">Newer →</a></li>
						  	</h:panelGroup>
						  	<h:panelGroup rendered="#{displayPostBean.post.newerPostTitle != null}">
						  		<li class="next">
						  			<h:outputLink value="#{request.contextPath}/posts/#{displayPostBean.post.newerPostTitle}"
						  				converter="com.sechristfamily.blog.PostTitleUrlConverter">
						  				Newer →
						  			</h:outputLink>
						  		</li>
						  	</h:panelGroup>
						</ul>

						<div id="socialShare">
							<h:outputLink value="//www.pinterest.com/pin/create/button/?url=#{displayPostBean.post.title}"
								converter="com.sechristfamily.blog.PostTitleUrlConverter" data-pin-do="buttonPin" data-pin-config="beside"
								class="pinterest">
								<img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" />
							</h:outputLink>
							<!-- Please call pinit.js only once per page -->
							<script type="text/javascript" async=""
								src="//assets.pinterest.com/js/pinit.js"></script>
								
							<div class="fb-share-button"
								data-type="button_count"></div>

							<!-- Place this tag where you want the share button to render. -->
							<div class="g-plus" data-action="share" data-annotation="bubble"
								style="margin: auto;"></div>

							<!-- Place this tag after the last share tag. -->
							<script type="text/javascript">
						  (function() {
						    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
						    po.src = 'https://apis.google.com/js/platform.js';
						    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
						  })();
						</script>
						</div>
					</div>
				</div>
				<div class="col-sm-4" id="disqus_container">
					<div id="disqus_thread" class="affix" data-spy="affix"
						data-offset-top="125"></div>
					<script type="text/javascript">
				/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
				var disqus_shortname = 'sechristblog'; // required: replace example with your forum shortname
				
				/* * * DON'T EDIT BELOW THIS LINE * * */
				(function() {
				var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
				dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
				(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
				})();
				</script>
					<noscript>
						Please enable JavaScript to view the <a
							href="http://disqus.com/?ref_noscript">comments powered by
							Disqus.</a>
					</noscript>
					<a href="http://disqus.com" class="dsq-brlink">comments powered
						by <span class="logo-disqus">Disqus</span>
					</a>
				</div>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>